# Generated by Django 2.0.1 on 2018-03-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astiasto', '0003_auto_20180308_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='firstname',
            new_name='Etunimi',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lastname',
            new_name='Sukunimi',
        ),
    ]
