# Generated by Django 2.0.1 on 2018-03-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astiasto', '0006_auto_20180308_2012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
