# Generated by Django 2.0.1 on 2018-03-08 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astiasto', '0007_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astiasto.Genre'),
        ),
    ]
