# Generated by Django 2.0.1 on 2018-03-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=40)),
                ('mail', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=15)),
                ('event', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
