# Generated by Django 2.0.1 on 2018-03-07 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astiasto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('max_amount', models.IntegerField()),
                ('price_otaniemi', models.FloatField()),
                ('price_others', models.FloatField()),
                ('img', models.ImageField(upload_to='')),
                ('genre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='astiasto.Genre')),
            ],
        ),
    ]
