# Generated by Django 2.0.1 on 2018-03-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astiasto', '0004_auto_20180308_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='Määrä',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phonenumber',
            new_name='Puhelinnumero',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='Päivänmäärä',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='event',
            new_name='Sähköposti',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='mail',
            new_name='Tapahtuma',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='place',
            new_name='Tapahtumapaikka',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='message',
            new_name='Viesti',
        ),
    ]
