# Generated by Django 2.0.1 on 2018-03-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astiasto', '0005_auto_20180308_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Määrä',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='Sähköposti',
            field=models.EmailField(max_length=254),
        ),
    ]
