# Generated by Django 2.0.1 on 2018-03-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astiasto', '0008_auto_20180308_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
